### PR TITLE
Update submodule

### PR DESCRIPTION
**Pull request by dzolnai**

### CODE REVIEW

**Review by welsinga — APPROVED** [review]

**Review by phavekes — CHANGES_REQUESTED** [review]
Can you fix the build error?
```/home/runner/work/tiqr-app-android/tiqr-app-android/app-core/data/src/main/java/org/tiqr/data/repository/AuthenticationRepository.kt: (146, 64): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?```

**Comment by dzolnai** [comment]
Yes I am working on it, Android Studio build cache can be sometimes a bit too aggressive, making builds even succeed which shouldn't 🙄

**Comment by dzolnai** [comment]
Fixed!

**Review by phavekes — APPROVED** [review]
Thanks for fixing

**Pull request merged**
